#!/bin/bash

# README
# Be inside polybench-c-3.2 before running
# add polybench.h and polybench.c to polybench-c-3.2 before running
# after first run comment out all mv instructions

# Putting all testbenches into big folder
declare -a arr=("medley" "linear-algebra" "kernels" "solvers" "datamining" "stencils")

for i in "${arr[@]}"
do
    mv $i/* .
    rm -r $i
done

NAME=yoojeen

# Linear Algebra Compilation
for d in */; do
    if [ $d = "utilities/" ]
    then
	continue
    fi	
    gcc -I utilities -lm -I $d utilities/polybench.c $d${d:0:${#string}-1}.c -o $d${d:0:${#string}-1}
done 
